#!/bin/bash
# Cuesync Sync Script
# Pulls latest code and regenerates cron from config.yaml

set -e

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$SCRIPT_DIR"

# Pull latest cuesync config
git pull origin main --quiet 2>/dev/null || true

# Pull latest maestro code (submodule)
cd maestro
git pull origin main --quiet 2>/dev/null || true
cd ..

# Regenerate crontab from config.yaml
python3 << 'PYTHON_SCRIPT'
import yaml
import subprocess
import os
from pathlib import Path

# Load config
config_path = Path(__file__).parent / 'config.yaml'
with open(config_path) as f:
    config = yaml.safe_load(f)

# Get absolute paths
cuesync_dir = Path(__file__).parent.absolute()
maestro_dir = cuesync_dir / 'maestro'
logs_dir = cuesync_dir / 'logs'

# Generate cron lines
lines = []
lines.append("# Auto-generated by cuesync - DO NOT EDIT MANUALLY")
lines.append("")

# Sync job
sync_schedule = config.get('sync_interval', '*/5 * * * *')
sync_cmd = f"cd {cuesync_dir} && ./sync.sh >> {logs_dir}/sync.log 2>&1"
lines.append(f"{sync_schedule} {sync_cmd}")
lines.append("")

# Cuesheet jobs
for cue in config.get('cuesheets', []):
    if not cue.get('enabled', True):
        continue

    name = cue['name']
    schedule = cue['schedule']
    description = cue.get('description', '')

    if description:
        lines.append(f"# {description}")

    cue_cmd = f"cd {maestro_dir} && .venv/bin/python3 gen/execute_cuesheet.py {name} >> {logs_dir}/{name}.log 2>&1"
    lines.append(f"{schedule} {cue_cmd}")
    lines.append("")

# Write to crontab
cron_content = '\n'.join(lines)

# Update crontab
process = subprocess.Popen(['crontab', '-'], stdin=subprocess.PIPE)
process.communicate(cron_content.encode())

if process.returncode == 0:
    print("✅ Cron updated from config.yaml")
else:
    print(f"❌ Failed to update cron (exit code: {process.returncode})")
    exit(1)
PYTHON_SCRIPT
